set1 = set()
value1 = int(input("Enter number: "))
set1.add(value1)
value2 = int(input("Enter number: "))
set1.add(value2)
value3 = int(input("Enter number: "))
set1.add(value3)
value4 = int(input("Enter number: "))
set1.add(value4)
value5 = int(input("Enter number: "))
set1.add(value5)
value6 = int(input("Enter number: "))
set1.add(value6)
value7 = int(input("Enter number: "))
set1.add(value7)
value8 = int(input("Enter number: "))
set1.add(value8)
print(set1)