marks = []
marks1 = int(input("Enter marks: "))
marks.append(marks1)
marks2 = int(input("Enter marks: "))
marks.append(marks2)
marks3 = int(input("Enter marks: "))
marks.append(marks3)
marks4 = int(input("Enter marks: "))
marks.append(marks4)
marks5 = int(input("Enter marks: "))
marks.append(marks5)
marks6 = int(input("Enter marks: "))
marks.append(marks6)
marks.sort()
print(marks)